"""
core/constants.py
Centralized constants for the application.
"""

class DSPyConfig:
    CLASSIFY_TIMEOUT_S = 45
    CLASSIFY_COOLDOWN_S = 120
    SEARCH_QUERY_TIMEOUT_S = 25
    CLASSIFY_MAX_TOKENS = 20
    MAX_SEARCH_QUERIES = 3
    CONFIDENCE_THRESHOLD_HIGH = 0.75
    CONFIDENCE_THRESHOLD_LOW = 0.4
    MODES = {}

class SearchConfig:
    DEFAULT_NUM_RESULTS = 5
    BM25_WEIGHT = 0.3
    SEMANTIC_WEIGHT = 0.7
    MAX_CONTEXT_CHARS = 15000
    JUNK_DOMAINS = {}
    SEARCH_RATE_LIMIT = 10
    SEARCH_RATE_LIMIT_WINDOW = 60.0
    SEARCH_CANDIDATE_MULTIPLIER = 2
    MAX_CONTEXT_RESULTS_MULTIPLIER = 1.5

class ModelConfig:
    MIN_AVAILABLE_MEMORY_GB = 2.0
    GPU_MAX_ALLOC_PERCENT_DEFAULT = 75
    DEFAULT_CONTEXT_LENGTH = 4096

class BackendConfig:
    LLAMA_SERVER_DEFAULT_PORT = 8080
    DEFAULT_TEMPERATURE = 0.7
    DEFAULT_MAX_TOKENS = 512
    DEFAULT_REPETITION_PENALTY = 1.1
    COMMON_STOP_TOKENS = []